# Generated by Django 5.0.4 on 2024-07-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_restaurantreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantReview',
        ),
    ]
