# Generated by Django 5.0.4 on 2024-06-23 17:25

from django.db import migrations


def create_only_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands_model = apps.get_model('main_app', 'UniqueBrands')

    db_alias = schema_editor.connection.alias

    all_brands = shoe.objects.values_list('brand', flat=True).distinct()

    for brand in all_brands:
        unique_brands_model.objects.using(db_alias).create(brand_name=brand)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_only_unique_brands)
    ]
