# Generated by Django 5.0.4 on 2024-07-11 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='movie',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
