# Generated by Django 5.0.4 on 2024-07-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_director_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actor_all_movies', to='main_app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='starring_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_starring_movies', to='main_app.actor'),
        ),
    ]
