# Generated by Django 5.0.4 on 2024-07-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_book_movie_music'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
    ]
