# Generated by Django 5.0.4 on 2024-07-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_book_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Model Book', 'verbose_name_plural': 'Models of type - Book'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Model Movie', 'verbose_name_plural': 'Models of type - Movie'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Model Music', 'verbose_name_plural': 'Models of type - Music'},
        ),
    ]
